# Generated by Django 2.1.1 on 2018-10-31 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),

            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('special_retail', models.DecimalField(decimal_places=2, max_digits=7)),
                ('regular_retail', models.DecimalField(decimal_places=2, max_digits=7)),
                ('upc_code', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('length', models.DecimalField(decimal_places=2, max_digits=7)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myToolWorkbench.Person')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            bases=('myToolWorkbench.person',),
        ),
    ]
