# Generated by Django 2.1.1 on 2018-11-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0005_remove_tool_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
