# Generated by Django 2.1.1 on 2018-11-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0006_tool_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='regular_retail',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='special_retail',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
