# Generated by Django 2.1.1 on 2018-11-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0007_auto_20181104_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='regular_retail',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='special_retail',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
