# Generated by Django 2.1.1 on 2018-11-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0008_auto_20181104_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='upc_code',
            field=models.IntegerField(null=True),
        ),
    ]
