# Generated by Django 2.1.1 on 2018-11-05 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0010_auto_20181104_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=128)),
                ('owner_first', models.CharField(max_length=30)),
                ('owner_last', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('day_visited', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myToolWorkbench.Business')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myToolWorkbench.Person')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='employees',
            field=models.ManyToManyField(through='myToolWorkbench.Employed', to='myToolWorkbench.Person'),
        ),
    ]
