# Generated by Django 2.1.1 on 2018-11-08 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0012_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myToolWorkbench.Tool')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myToolWorkbench.UserAccount')),
            ],
            bases=('myToolWorkbench.tool',),
        ),
        migrations.CreateModel(
            name='ToolInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workbench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myToolWorkbench.UserAccount')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='no address', max_length=150),
        ),
        migrations.AddField(
            model_name='toolinstance',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myToolWorkbench.Workbench'),
        ),
        migrations.AddField(
            model_name='toolinstance',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myToolWorkbench.Tool'),
        ),
    ]
