# Generated by Django 2.1.1 on 2018-11-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0013_auto_20181107_1918'),
        ('myToolWorkbench', '0013_auto_20181108_1651'),
    ]

    operations = [
    ]
