# Generated by Django 2.1.1 on 2018-11-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0014_merge_20181121_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolinstance',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
