# Generated by Django 2.1.1 on 2018-11-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0015_auto_20181129_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='user_account',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='myToolWorkbench.UserAccount'),
        ),
    ]
