# Generated by Django 2.1.1 on 2018-11-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0016_business_user_account'),
        ('myToolWorkbench', '0015_auto_20181129_1405'),
    ]

    operations = [
    ]
