# Generated by Django 2.1.1 on 2018-11-29 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0019_auto_20181129_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
