# Generated by Django 2.1.1 on 2018-11-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myToolWorkbench', '0022_toolinstance_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolinstance',
            name='owner',
        ),
        migrations.AlterField(
            model_name='toolinstance',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myToolWorkbench.Workbench'),
        ),
    ]
